server:
  port: 8080
spring:
  application:
    name: Gateway-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
    config:
      discovery:
        enabled: true
        service-id: config-server
  config:
    import: 'optional:configserver:'
  main:
    allow-bean-definition-overriding: true
